version: "2"

linters:
  default: all
  disable:
    - godox
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/anttikivi/reginald
            - github.com/anttikivi/go-semver
            - github.com/pelletier/go-toml/v2
            - github.com/spf13/pflag
    errcheck:
      disable-default-exclusions: false
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    varnamelen:
      max-distance: 50

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
