version: "2"

linters:
  default: all
  disable:
    - godox
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/anttikivi/reginald
    errcheck:
      disable-default-exclusions: false
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    varnamelen:
      max-distance: 30

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
