version: "2"

linters:
  default: all
  disable:
    - godox
  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - funlen
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/anttikivi/reginald
            - github.com/anttikivi/go-semver
            - golang.org/x/sync
            - github.com/pelletier/go-toml/v2
            - github.com/spf13/pflag
    errcheck:
      disable-default-exclusions: false
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    funlen:
      lines: 100
      ignore-comments: true
    goconst:
      find-duplicates: true
      ignore-string-values:
        - "^stderr$" # TODO: check this again later, maybe the ignore should be removed
      min-occurrences: 3
    musttag:
      functions:
        - name: (*github.com/pelletier/go-toml/v2.Decoder).Decode
          tag: toml
          arg-pos: 0
    varnamelen:
      max-distance: 50
      ignore-decls:
        - wg sync.WaitGroup

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
