version: "2"

linters:
  default: all
  disable:
    - godox
  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - funlen
  settings:
    cyclop:
      max-complexity: 20
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
      disable-dec-order-check: false
      disable-init-func-first-check: false
      disable-dec-num-check: true
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/anttikivi/reginald
            - github.com/anttikivi/go-semver
            - github.com/go-viper/mapstructure/v2
            - github.com/pelletier/go-toml/v2
            - github.com/spf13/afero
            - github.com/spf13/pflag
            - golang.org/x/sync
            - golang.org/x/term
    errcheck:
      disable-default-exclusions: false
    exhaustruct:
      exclude:
        - '^github\.com/anttikivi/reginald/pkg/rpp\.Message$'
    funlen:
      lines: 100
      statements: 60
      ignore-comments: true
    goconst:
      find-duplicates: true
      ignore-string-values:
        - "^stderr$" # TODO: check this again later, maybe the ignore should be removed
      min-occurrences: 3
    musttag:
      functions:
        - name: (*github.com/pelletier/go-toml/v2.Decoder).Decode
          tag: toml
          arg-pos: 0
    varnamelen:
      max-distance: 50
      ignore-decls:
        - eg *errgroup.Group
        - fs afero.Fs
        - g *errgroup.Group
        - id rpp.ID
        - mu sync.Mutex
        - wg sync.WaitGroup

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
