#!/usr/bin/env bash

# Copyright 2025 Antti Kivi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

if [[ -z "$1" ]]; then
  echo "No version given as an argument" >&2
  exit 1
fi

golines_version="$1"
checksum_file="golines_${golines_version}_checksums.txt"
archive_file="golines_${golines_version}_$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m).tar.gz"

if [[ "$(uname)" == "Darwin" ]]; then
  archive_file="golines_${golines_version}_darwin_all.tar.gz"
fi

destination="$(go env GOPATH)/bin/golines"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

cd "${script_dir}/.."

mkdir tmp

cd tmp

curl -sSfLO "https://github.com/segmentio/golines/releases/download/v${golines_version}/${checksum_file}"
curl -sSfLO "https://github.com/segmentio/golines/releases/download/v${golines_version}/${archive_file}" -o ./tmp/golines.tar.gz
sha256sum -c --ignore-missing "${checksum_file}"

if [[ -f "${destination}" ]]; then
  rm "${destination}"
fi

if [[ ! -d "$(dirname "${destination}")" ]]; then
  mkdir -p "$(dirname "${destination}")"
fi

tar --strip-components=1 -C "$(dirname "${destination}")" -xf "${archive_file}" "$(basename "${archive_file}" ".tar.gz")/golines"

cd ..

rm -rf tmp
