name: Lint

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up the Go toolchain
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod

      - name: Verify and download dependencies
        run: |
          go mod verify
          go mod download

      - name: Run the linter
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.6
