name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
          - macos-15
          - macos-14
          - macos-13

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod

      - name: Display the platform information for Go
        run: |
          go env GOOS
          go env GOARCH
          go version

      - name: Verify and download dependencies
        run: |
          go mod verify
          go mod download

      - name: Run the unit tests
        run: make test GOFLAGS="-v"

  race-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
          - macos-15
          - macos-14
          - macos-13

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod

      - name: Display the platform information for Go
        run: |
          go env GOOS
          go env GOARCH
          go version

      - name: Verify and download dependencies
        run: |
          go mod verify
          go mod download

      - name: Run the tests
        run: make test GOFLAGS="-race -v"

  # TODO: Create the integration tests.
